const express = require('express'), request = require('supertest');
jest.mock('../../contexts', () => ({ inventory: { reads: { list:jest.fn(), detail:jest.fn(), movements:jest.fn(), context:jest.fn() }, commands:{ catalogue:jest.fn(), entry:jest.fn(), adjust:jest.fn(), consume:jest.fn(), correct:jest.fn(), returnItems:jest.fn(), recover:jest.fn() } } }));
jest.mock('../../services/business-config.service',()=>({getActiveModules:async()=>['veterinary','grooming','retail']}));
const { inventory } = require('../../contexts');
const { allowVeterinaryDashboard } = require('../../middleware/allowVeterinaryDashboard');
const routes = require('../../routes/dashboard/inventory.routes');
function app(role='admin',permissions=[]) {const a=express();a.use(express.json());a.use((req,res,next)=>{req.tenant={tenantId:'trusted-tenant'};req.actor={type:role,staffId:'trusted-staff',sessionVersion:1,accessPermissions:permissions};next();});a.use(allowVeterinaryDashboard,routes);return a;}
beforeEach(()=>jest.resetAllMocks());
test('read identity comes from authenticated request, never query',async()=>{inventory.reads.list.mockResolvedValue({data:[]});const r=await request(app()).get('/inventory/products?tenantId=foreign');expect(r.status).toBe(200);expect(inventory.reads.list.mock.calls[0][0]).toEqual(expect.objectContaining({tenantId:'trusted-tenant',actor:expect.objectContaining({staffId:'trusted-staff'})}));});
test('command forwards idempotency header and scoped route product',async()=>{inventory.commands.entry.mockResolvedValue({operationId:'ok'});const r=await request(app()).post('/inventory/products/real/entries').set('Idempotency-Key','11111111-2222-4333-8444-555555555555').send({quantity:2,productId:'forged'});expect(r.status).toBe(200);expect(inventory.commands.entry.mock.calls[0][0]).toEqual(expect.objectContaining({tenantId:'trusted-tenant',kind:'register_entry',operationKey:'11111111-2222-4333-8444-555555555555',command:expect.objectContaining({productId:'real'})}));});
test('professional consumption requires explicit permission without cash',async()=>{expect((await request(app('vet')).post('/inventory/consumptions').send({})).status).toBe(403);inventory.commands.consume.mockResolvedValue({operationId:'saved'});expect((await request(app('vet',['inventory_consume'])).post('/inventory/consumptions').send({})).status).toBe(200);});
test.each(['receptionist','vet','groomer'])('%s cannot adjust, correct or return stock',async role=>{for(const path of ['/inventory/products/p/adjustments','/inventory/consumptions/o/corrections','/transactions/t/inventory-returns'])expect((await request(app(role,['cash','inventory_consume'])).post(path).send({})).status).toBe(403);});
test('reception can read availability and operational context but not full movements',async()=>{inventory.reads.context.mockResolvedValue({scope:'hash'});expect((await request(app('receptionist')).get('/inventory/context')).status).toBe(200);expect((await request(app('receptionist')).get('/inventory/products/p/movements')).status).toBe(403);});
test('domain conflict is explicit, infrastructure failure is uncertain',async()=>{inventory.commands.entry.mockRejectedValueOnce(Object.assign(new Error('Changed'),{status:409,code:'STOCK_COUNT_CHANGED'}));expect((await request(app()).post('/inventory/products/p/entries').send({})).body.code).toBe('STOCK_COUNT_CHANGED');inventory.commands.entry.mockRejectedValueOnce(new Error('offline'));const r=await request(app()).post('/inventory/products/p/entries').send({});expect(r.status).toBe(503);expect(r.body.code).toBe('RESULT_UNCERTAIN');});
