"use client";
import { useCallback, useEffect, useState } from "react";
import { Package, PackagePlus, Search, RotateCw, Plus, ClipboardList } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useDashboardAccess } from "@/components/dashboard/dashboard-access-provider";
import { proxyUrl } from "@/lib/api";
import { useTenant } from "@/lib/use-tenant";
import { formatPosMoney } from "@/lib/pos-checkout";
import { useInventoryOperation } from "@/lib/use-inventory-operation";
import { MOVEMENT_NAMES, USE_NAMES, type InventoryProduct, type InventoryMovement, type ProductUse } from "@/lib/inventory";
import { InventoryOperationStatus } from "./operation-status";
import { ProductForm } from "./product-form";
import { StockForm } from "./stock-form";
import { ConsumptionButton } from "./consumption-button";
const selectClass="h-11 rounded-xl border bg-white px-3 text-sm";
const date=(value:string)=>new Date(value).toLocaleString("es-CO",{timeZone:"America/Bogota",dateStyle:"short",timeStyle:"short"});
export function InventoryWorkspace() {
  const access=useDashboardAccess(),tenant=useTenant(),manage=!!access?.capabilities.inventory_manage;
  const [rows,setRows]=useState<InventoryProduct[]>([]),[search,setSearch]=useState(""),[use,setUse]=useState(""),[status,setStatus]=useState(""),[inactive,setInactive]=useState(false),[cursor,setCursor]=useState(""),[next,setNext]=useState<string|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  const [editor,setEditor]=useState<InventoryProduct|"new"|null>(null),[selected,setSelected]=useState<InventoryProduct|null>(null),[stock,setStock]=useState<{product:InventoryProduct;mode:"entry"|"count"|"correction";source?:InventoryMovement}|null>(null);
  const [movements,setMovements]=useState<InventoryMovement[]>([]),[historyCursor,setHistoryCursor]=useState<string|null>(null),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState("");
  const saved=useCallback(()=>{setRefresh(n=>n+1);},[]);
  const operation=useInventoryOperation(saved);
  const url=useCallback((path:string)=>proxyUrl(path+(tenant?(path.includes("?")?"&":"?")+"tenantId="+encodeURIComponent(tenant):"")),[tenant]);
  useEffect(()=>{
    if(!access?.capabilities.inventory_read)return;
    const abort=new AbortController();const timer=setTimeout(async()=>{
      setBusy(true);setError("");
      try { const params=new URLSearchParams({search,use,status,includeInactive:inactive?"1":"0",limit:"30"});if(cursor)params.set("cursor",cursor);
        const r=await fetch(url("/api/dashboard/inventory/products?"+params),{cache:"no-store",signal:abort.signal});const data=await r.json();if(!r.ok)throw new Error(data.error??"No se pudo cargar el inventario.");
        if(!abort.signal.aborted){setRows(data.data);setNext(data.nextCursor);}
      }catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:"Inventario no disponible.");}finally{if(!abort.signal.aborted)setBusy(false);}
    },200);return()=>{clearTimeout(timer);abort.abort();};
  },[search,use,status,inactive,cursor,refresh,url,access?.capabilities.inventory_read]);
  async function history(p:InventoryProduct,after?:string) {
    setHistoryBusy(true);setHistoryError("");
    try{const r=await fetch(url(`/api/dashboard/inventory/products/${p.id}/movements${after?"?cursor="+after:""}`),{cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error??"No se pudo cargar el historial.");setMovements(list=>after?[...list,...data.data]:data.data);setHistoryCursor(data.nextCursor);}catch(e){setHistoryError(e instanceof Error?e.message:"Historial no disponible.");}finally{setHistoryBusy(false);}
  }
  async function openDetail(p:InventoryProduct) {setSelected(p);setMovements([]);setHistoryCursor(null);if(manage)await history(p);}
  if(!access)return <p role="status" className="p-6">Comprobando permisos…</p>;
  if(!access.capabilities.inventory_read)return <p className="p-6">Tu perfil no tiene acceso al inventario.</p>;
  const disabled=operation.busy||operation.pending.length>0;
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="rounded-2xl bg-teal-100 p-3 text-primary"><Package className="h-7 w-7"/></div><div><h1 className="text-3xl font-bold tracking-tight">Inventario</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Productos e insumos con existencias, lotes y vencimientos.</p></div></div><div className="flex flex-wrap gap-2">{access.capabilities.inventory_consume&&<ConsumptionButton area={access.capabilities.clinical?"veterinary":"grooming"} onSaved={saved}/>} {manage&&<Button disabled={disabled} onClick={()=>setEditor("new")}><Plus className="mr-2 h-4 w-4"/>Nuevo producto</Button>}</div></header>
    <InventoryOperationStatus operation={operation}/>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid items-end gap-4 border-b p-5 md:grid-cols-[minmax(200px,1fr)_180px_210px_auto]"><label className="text-sm font-semibold">Buscar producto<div className="relative mt-2"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={search} onChange={e=>{setSearch(e.target.value);setCursor("");}} className="pl-10 font-normal" placeholder="Nombre, código o barras"/></div></label><label className="text-sm font-semibold">Uso<select value={use} onChange={e=>{setUse(e.target.value);setCursor("");}} className={selectClass+" mt-2 w-full font-normal"}><option value="">Todos mis productos</option>{(["retail","veterinary","grooming"] as ProductUse[]).filter(u=>access.activeModules.includes(u)&&(manage||(u==="retail"?access.capabilities.cash:u==="veterinary"?access.capabilities.clinical:access.capabilities.grooming))).map(u=><option key={u} value={u}>{USE_NAMES[u]}</option>)}</select></label><label className="text-sm font-semibold">Existencias<select value={status} onChange={e=>{setStatus(e.target.value);setCursor("");}} className={selectClass+" mt-2 w-full font-normal"}><option value="">Todos los saldos</option><option value="low">En mínimo o por debajo</option><option value="expiring">Vencen en 30 días</option><option value="expired">Con unidades vencidas</option></select></label><Button variant="outline" disabled={busy} onClick={()=>setRefresh(n=>n+1)}><RotateCw className={`mr-2 h-4 w-4 ${busy?"animate-spin":""}`}/>Actualizar</Button></div>
      <div className="flex flex-wrap items-center justify-between gap-3 bg-muted/30 px-5 py-3 text-xs text-muted-foreground"><p>Disponibles: unidades aptas para venta o uso. Los vencidos conservan su saldo físico.</p>{manage&&<label className="flex items-center gap-2"><input type="checkbox" checked={inactive} onChange={e=>{setInactive(e.target.checked);setCursor("");}} className="accent-teal-700"/>Incluir desactivados</label>}</div>
      {error?<div role="alert" className="p-6 text-red-800">{error}<Button className="ml-3" variant="outline" onClick={()=>setRefresh(n=>n+1)}>Reintentar</Button></div>:busy?<p role="status" className="p-8 text-sm text-muted-foreground">Consultando existencias…</p>:!rows.length?<div className="p-10 text-center"><Package className="mx-auto h-9 w-9 text-muted-foreground"/><h2 className="mt-3 font-semibold">No hay productos en esta vista</h2><p className="mt-2 text-sm text-muted-foreground">{search||use||status?"Prueba otra búsqueda o cambia los filtros.":manage?"Registra tu primer producto y luego ingresa las unidades recibidas.":"Administración puede registrar los productos de tu área."}</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left text-sm"><thead className="border-y bg-muted/30 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Producto / presentación</th><th className="px-4 py-3 font-medium">Área</th><th className="px-4 py-3 text-right font-medium">Disponibles</th><th className="px-4 py-3 text-right font-medium">Físicas</th>{access.capabilities.cash&&<th className="px-4 py-3 text-right font-medium">Precio COP</th>}<th className="px-5 py-3 text-right font-medium">Acciones</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} className="border-b last:border-0 hover:bg-muted/20"><td className="px-5 py-4"><button className="text-left font-semibold text-primary underline-offset-4 hover:underline" onClick={()=>void openDetail(p)}>{p.name}</button><p className="mt-1 text-xs text-muted-foreground">{p.internalCode} · {p.presentation}</p><div className="mt-2 flex flex-wrap gap-1.5">{!p.active&&<span className="rounded bg-muted px-2 py-0.5 text-xs">Desactivado</span>}{p.lowStock&&<span className="rounded bg-amber-50 px-2 py-0.5 text-xs text-amber-900">Existencia mínima: {p.stockMinimum}</span>}{BigInt(p.expired)>BigInt(0)&&<span className="rounded bg-red-50 px-2 py-0.5 text-xs text-red-800">{p.expired} vencidas</span>}{p.lots.some(l=>l.expiresSoon&&l.physical>0)&&<span className="rounded bg-amber-50 px-2 py-0.5 text-xs text-amber-900">Próximo vencimiento</span>}</div></td><td className="px-4 py-4 text-xs text-muted-foreground">{p.uses.map(u=>USE_NAMES[u]).join(" · ")}</td><td className="px-4 py-4 text-right text-lg font-bold tabular-nums">{p.available}</td><td className="px-4 py-4 text-right tabular-nums text-muted-foreground">{p.physical}</td>{access.capabilities.cash&&<td className="px-4 py-4 text-right tabular-nums">{p.salePrice?formatPosMoney(p.salePrice):"—"}</td>}<td className="px-5 py-4"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>void openDetail(p)}>Ver detalle</Button>{manage&&p.active&&<Button size="sm" disabled={disabled} onClick={()=>setStock({product:p,mode:"entry"})}><PackagePlus className="mr-1 h-4 w-4"/>Entrada</Button>}</div></td></tr>)}</tbody></table></div>}
      <div className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-4"><span className="text-xs text-muted-foreground">{rows.length} productos en esta página</span><div className="flex gap-2">{cursor&&<Button size="sm" variant="outline" onClick={()=>setCursor("")}>Primera página</Button>}{next&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setCursor(next)}>Siguientes productos</Button>}</div></div>
    </section>
    {editor&&<ProductForm key={editor==="new"?"new":editor.id} product={editor==="new"?undefined:editor} onClose={()=>setEditor(null)} onSaved={saved}/>}
    {stock&&<StockForm key={stock.product.id+stock.mode} {...stock} onClose={()=>setStock(null)} onSaved={saved}/>}
    <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="flex max-h-[90dvh] w-[calc(100%-2rem)] max-w-4xl flex-col overflow-hidden border-border bg-white shadow-xl"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.internalCode} · {selected?.presentation} · {selected?.category}</DialogDescription></DialogHeader>{selected&&<div className="space-y-6 overflow-y-auto px-6 pb-6"><dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Disponibles",selected.available],["Físicas",selected.physical],["Vencidas",selected.expired],["Mínimo",selected.stockMinimum]].map(([label,value])=><div key={label} className="rounded-xl border bg-muted/20 p-4"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-2 text-2xl font-bold tabular-nums">{value}</dd></div>)}</dl>
      {manage&&<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={disabled} onClick={()=>{setEditor(selected);setSelected(null);}}>Editar producto</Button><Button variant="outline" disabled={disabled||!selected.lots.length} onClick={()=>{setStock({product:selected,mode:"count"});setSelected(null);}}><ClipboardList className="mr-2 h-4 w-4"/>Conteo físico / retiro</Button><Button variant="outline" disabled={disabled||!operation.ready} onClick={async()=>{if(await operation.execute("set_product_active",`/api/dashboard/inventory/products/${selected.id}`,{active:!selected.active,expectedVersion:selected.metadataVersion},`${selected.active?"Desactivar":"Activar"} ${selected.name}`,"PATCH"))setSelected(null);}}>{selected.active?"Desactivar":"Activar"}</Button><p className="w-full text-xs text-muted-foreground">Costo de referencia: {formatPosMoney(selected.referenceCost??0)} · Desactivar conserva el historial y bloquea nuevos usos.</p></div>}
      <section><h2 className="mb-3 font-semibold">Lotes y existencias</h2>{!selected.lots.length?<p className="text-sm text-muted-foreground">No hay entradas registradas todavía.</p>:<div className="space-y-2">{selected.lots.map(l=><div key={l.id} className="flex flex-wrap justify-between gap-2 rounded-xl border p-4 text-sm"><div><strong>{l.lotCode??"Sin lote"}</strong><p className="mt-1 text-xs text-muted-foreground">{l.expiresOn?`Vence: ${l.expiresOn}`:"Sin fecha de vencimiento"}{l.expiresSoon?" · Próximos 30 días":""}</p></div><p>{l.available} disponibles · {l.physical} físicas</p></div>)}</div>}</section>
      {manage&&<section><h2 className="mb-3 font-semibold">Historial de movimientos</h2>{historyError&&<p role="alert" className="text-sm text-red-800">{historyError}<Button size="sm" variant="ghost" onClick={()=>void history(selected)}>Reintentar</Button></p>}{movements.map(m=><div key={m.id} className="border-t py-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{MOVEMENT_NAMES[m.kind]??m.kind}</strong><span className="font-semibold tabular-nums">{m.stockDelta>0?"+":""}{m.stockDelta} unidades · Saldo del lote: {m.balanceAfter}</span></div><p className="mt-1 text-xs text-muted-foreground">{date(m.occurredAt)} · {m.actorName} · {m.lotCodeSnapshot??"Sin lote"}{m.entryUnitCost!=null?` · Costo unitario ${formatPosMoney(Number(m.entryUnitCost))}`:""}</p>{m.reason&&<p className="mt-2 whitespace-pre-wrap break-words text-sm">{m.reason}</p>}{m.kind==="consumption"&&<Button disabled={disabled} size="sm" variant="outline" className="mt-2" onClick={()=>{setStock({product:selected,mode:"correction",source:m});setSelected(null);}}>Corregir unidades no utilizadas</Button>}</div>)}{historyBusy&&<p role="status" className="text-sm">Cargando movimientos…</p>}{!movements.length&&!historyBusy&&!historyError&&<p className="text-sm text-muted-foreground">Sin movimientos registrados.</p>}{historyCursor&&<Button variant="outline" size="sm" disabled={historyBusy} onClick={()=>void history(selected,historyCursor)}>Ver movimientos anteriores</Button>}</section>}
    </div>}<DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}>Cerrar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
