"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useDashboardAccess } from "@/components/dashboard/dashboard-access-provider";
import { useInventoryOperation } from "@/lib/use-inventory-operation";
import { USE_NAMES, type InventoryProduct, type ProductUse } from "@/lib/inventory";
import { InventoryOperationStatus } from "./operation-status";
const selectClass="mt-2 h-11 w-full rounded-xl border bg-white px-3 text-sm font-normal";
export function ProductForm({ product, onClose, onSaved }: { product?: InventoryProduct; onClose:()=>void; onSaved:()=>void|Promise<void> }) {
  const access=useDashboardAccess(),operation=useInventoryOperation(onSaved);
  const [values,setValues]=useState({name:product?.name??"",internalCode:product?.internalCode??"",barcode:product?.barcode??"",category:product?.category??"",presentation:product?.presentation??"",referenceCost:String(product?.referenceCost??""),salePrice:String(product?.salePrice??""),stockMinimum:String(product?.stockMinimum??0),lotPolicy:product?.lotPolicy??"untracked"});
  const [uses,setUses]=useState<ProductUse[]>(product?.uses??[]),[saved,setSaved]=useState(false);
  const locked=operation.busy||operation.pending.length>0||saved;
  const change=(field:keyof typeof values,value:string)=>setValues(v=>({...v,[field]:value}));
  async function submit(e:React.FormEvent) {e.preventDefault();const ok=await operation.execute(product?"update_product":"create_product",`/api/dashboard/inventory/products${product?"/"+product.id:""}`,{...values,barcode:values.barcode.trim()||null,salePrice:values.salePrice.trim().replace(",",".")||null,referenceCost:values.referenceCost.replace(",","."),stockMinimum:Number(values.stockMinimum),uses,...(product?{expectedVersion:product.metadataVersion}:{})},product?`Editar ${product.name}`:"Nuevo producto",product?"PATCH":"POST");if(ok)setSaved(true);}
  return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="flex max-h-[90dvh] w-[calc(100%-2rem)] max-w-3xl flex-col overflow-hidden border-border bg-white shadow-xl"><DialogHeader><DialogTitle>{product?"Editar producto":"Registrar producto o insumo"}</DialogTitle><DialogDescription>Define una presentación completa. Las existencias se registran por separado mediante entradas.</DialogDescription></DialogHeader><form className="flex min-h-0 flex-col" onSubmit={submit}><div className="space-y-5 overflow-y-auto px-6 pb-6"><InventoryOperationStatus operation={operation}/><fieldset disabled={locked} className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Nombre<Input required maxLength={160} value={values.name} onChange={e=>change("name",e.target.value)} className="mt-2 font-normal" placeholder="Ej. Champú para piel sensible" /></label><label className="text-sm font-semibold">Código interno<Input required maxLength={64} value={values.internalCode} onChange={e=>change("internalCode",e.target.value)} className="mt-2 font-normal" placeholder="Ej. CH-001" /></label><label className="text-sm font-semibold">Código de barras (opcional)<Input maxLength={80} value={values.barcode} onChange={e=>change("barcode",e.target.value)} className="mt-2 font-normal" placeholder="Conserva los ceros iniciales" /></label><label className="text-sm font-semibold">Categoría<Input required maxLength={80} value={values.category} onChange={e=>change("category",e.target.value)} className="mt-2 font-normal" placeholder="Ej. Medicamentos, alimento, aseo" /></label><label className="text-sm font-semibold">Presentación<Input required disabled={!!product&&product.stockRevision>0} maxLength={80} value={values.presentation} onChange={e=>change("presentation",e.target.value)} className="mt-2 font-normal" placeholder="Ej. Frasco de 250 ml" /></label></div>
    <fieldset className="rounded-xl border p-4"><legend className="px-2 text-sm font-semibold">¿Dónde se utiliza?</legend><div className="flex flex-wrap gap-5">{(["retail","veterinary","grooming"] as ProductUse[]).filter(u=>access?.activeModules.includes(u)||uses.includes(u)).map(u=><label key={u} className="flex items-center gap-2 text-sm"><input type="checkbox" className="size-4 accent-teal-700" checked={uses.includes(u)} onChange={e=>setUses(list=>e.target.checked?[...list,u]:list.filter(x=>x!==u))}/>{USE_NAMES[u]}</label>)}</div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Costo de referencia (COP)<Input required inputMode="decimal" value={values.referenceCost} onChange={e=>change("referenceCost",e.target.value)} className="mt-2 font-normal" placeholder="Ej. 12000"/><span className="mt-1 block text-xs font-normal text-muted-foreground">Visible solo para administración.</span></label>{uses.includes("retail")&&<label className="text-sm font-semibold">Precio de venta por unidad (COP)<Input required inputMode="decimal" value={values.salePrice} onChange={e=>change("salePrice",e.target.value)} className="mt-2 font-normal" placeholder="Ej. 18000" /></label>}<label className="text-sm font-semibold">Existencia mínima (unidades)<Input required type="number" min={0} step={1} value={values.stockMinimum} onChange={e=>change("stockMinimum",e.target.value)} className="mt-2 font-normal" /></label><label className="text-sm font-semibold">Control del producto<select disabled={!!product&&product.stockRevision>0} value={values.lotPolicy} onChange={e=>change("lotPolicy",e.target.value)} className={selectClass}><option value="untracked">Sin lote</option><option value="lot">Por lote</option><option value="lot_expiry">Por lote y vencimiento</option></select></label></div>
    <p className="rounded-xl bg-muted p-3 text-xs text-muted-foreground">Ingresa valores sin separadores de miles. Después del primer movimiento, la presentación y el control de lotes se conservan para mantener el historial.</p>
  </fieldset></div><DialogFooter><Button type="button" variant="outline" onClick={onClose}>{saved?"Cerrar":"Cancelar"}</Button>{!saved&&<Button type="submit" disabled={locked||!operation.ready||!uses.length}>{operation.busy?"Guardando…":"Guardar producto"}</Button>}</DialogFooter></form></DialogContent></Dialog>;
}
