"use client";
import { useState } from "react";
import { Undo2 } from "lucide-react";
import { useDashboardAccess } from "@/components/dashboard/dashboard-access-provider";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useInventoryOperation } from "@/lib/use-inventory-operation";
import type { Transaction } from "@/lib/transactions";
import { InventoryOperationStatus } from "./operation-status";
export function InventoryReturnButton({ transaction, onSaved }: {transaction:Transaction;onSaved:()=>void|Promise<void>}) {
  const access=useDashboardAccess(),[open,setOpen]=useState(false);
  if(!access?.capabilities.inventory_manage||transaction.status!=="voided"||transaction.origin!=="manual_pos_sale"||!transaction.items.some(i=>i.productId&&!i.inventoryReturn))return null;
  return <><Button variant="outline" onClick={()=>setOpen(true)}><Undo2 className="mr-2 h-4 w-4"/>Recibir devolución</Button>{open&&<ReturnDialog transaction={transaction} onClose={()=>setOpen(false)} onSaved={onSaved}/>}</>;
}
function ReturnDialog({transaction,onClose,onSaved}:{transaction:Transaction;onClose:()=>void;onSaved:()=>void|Promise<void>}) {
  const operation=useInventoryOperation(onSaved),[items,setItems]=useState<Record<string,"restock"|"discard">>({}),[reason,setReason]=useState(""),[saved,setSaved]=useState(false);
  const locked=operation.busy||operation.pending.length>0||saved;
  async function submit(e:React.FormEvent) {e.preventDefault();if(await operation.execute("return_sale_items",`/api/dashboard/transactions/${transaction.id}/inventory-returns`,{reason:reason.trim(),items:Object.entries(items).map(([transactionItemId,disposition])=>({transactionItemId,disposition}))},"Devolución de mercancía"))setSaved(true);}
  return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="flex max-h-[90dvh] w-[calc(100%-2rem)] max-w-2xl flex-col overflow-hidden border-border bg-white shadow-xl"><DialogHeader><DialogTitle>Recibir mercancía de una venta anulada</DialogTitle><DialogDescription>Registra las líneas completas que recibiste. La mercancía apta repone su lote original; la dañada o vencida queda como no apta. Este registro no realiza un reembolso bancario.</DialogDescription></DialogHeader><form className="flex min-h-0 flex-col" onSubmit={submit}><div className="space-y-4 overflow-y-auto px-6 pb-5"><InventoryOperationStatus operation={operation}/><fieldset disabled={locked} className="space-y-4">{transaction.items.filter(i=>i.productId).map(i=><div key={i.id} className="rounded-xl border p-4"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 size-4 accent-teal-700" checked={!!items[i.id]} disabled={!!i.inventoryReturn} onChange={e=>setItems(previous=>{const next={...previous};if(e.target.checked)next[i.id]="restock";else delete next[i.id];return next;})}/><span className="text-sm"><strong>{i.description}</strong><span className="mt-1 block text-xs text-muted-foreground">{i.quantity} unidades · {i.presentation}{i.inventoryReturn?" · Devolución registrada":""}</span></span></label>{items[i.id]&&<label className="mt-3 block text-xs font-semibold">Estado de la mercancía<select className="mt-2 h-11 w-full rounded-xl border px-3 text-sm font-normal" value={items[i.id]} onChange={e=>setItems(previous=>({...previous,[i.id]:e.target.value as "restock"|"discard"}))}><option value="restock">Apta · reponer existencias</option><option value="discard">Dañada o vencida · no reponer existencias</option></select></label>}</div>)}<label className="block text-sm font-semibold">Motivo de la devolución<textarea required maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 block w-full rounded-xl border p-3 font-normal focus-visible:outline-2 focus-visible:outline-primary"/></label></fieldset></div><DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cerrar</Button>{!saved&&<Button type="submit" disabled={locked||!operation.ready||!Object.keys(items).length}>{operation.busy?"Guardando…":"Guardar recepción"}</Button>}</DialogFooter></form></DialogContent></Dialog>;
}
